config/routes.rb
Rails.application.routes.draw do

  resources :places
  get 'welcome/index'

  root 'welcome#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  	@places = Place.all
  end

  def show
  	@place = Place.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LekkerPlekka</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

<% @places.each do |place| %>
	<p>
		Name:        <%= place.name %>        Address:        <%= place.address%> <%= link_to 'show', place %>
	</p>


<% end %>

app/views/places/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<%= link_to 'Back', places_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>